@echo off

REM THEMEDEF, Default Installer Theme.

REM Screen Foreground, Background and Fill Character
set TSF=Gray
set TSB=Blue
set TSC=0x20

REM Title Bar Foreground, Background and Highlight Colors
set TTF=Black
set TTB=Gray
set TTH=Black

REM Window Foreground, Background, Highlight Warning color
REM Progress Bar Colors, Choice attribute and Box Style
set TFF=Black
set TFH=Blue
set TFX=LightRed
set TFP=Blue
set TFB=Gray
set TFS=single shadow
set TFC=0x1e

REM Control-C Foreground, Background and Highlight Colors
REM Choice attribute and Box Style
set TCF=White
set TCH=Yellow
set TCB=Red
set TCS=double shadow
set TCC=0x1e

REM Pause Bar and Timer Countdown Colors
set TPB=Blue
set TPF=LightGreen
set TPH=LightCyan

REM Text Input Colors.
set TQF=White
set TQB=Blue

verrlvl 0
