@echo off

REM THEMEADV, Advanced Installer Theme.

REM Screen Foreground, Background and Fill Character
set TSF=Gray
set TSB=Black
set TSC=0xB0

REM Title Bar Foreground, Background and Highlight Colors
set TTF=White
set TTB=Red
set TTH=Yellow

REM Window Foreground, Background and Highlight Colors
set TFF=White
set TFH=LightGreen
set TFB=Red
set TFP=Yellow
set TFS=double shadow
set TFC=0x1e

REM Control-C Foreground, Background and Highlight Colors
set TCF=White
set TCH=Yellow
set TCB=Red
set TCS=single shadow
set TCC=0x1f

REM Pause Bar and Clock Colors
set TPB=Red
set TPF=White
set TPH=Yellow

REM Text Input Colors.
set TQF=Yellow
set TQB=Blue

verrlvl 0
