@echo off

REM Reserved for testing system compatibility and requirements are met.

REM To automatically include this file on the installer, add FDCHECK.BAT to
REM the MKSETUP.LST installer setup file list.

REM If a language file FDCHECK.DEF exists, it will be automatically loaded
REM prior to running this file.

REM If requirements are not met, set errorlevel to 1. Also, it may be useful
REM to the user to set the FERROR message and/or include a custom FDERROR.BAT
REM as well.

verrlvl 0