@echo off

REM Reserved for splash screen or log display.

REM To automatically include this file on the installer, add FDSPLASH.BAT to
REM the MKSETUP.LST installer setup file list.

REM If a language file FDSPLASH.DEF exists, it will be automatically loaded
REM prior to running this file.

REM This file is called after STAGE000 (Configuration) and STAGE100
REM (Installation Check). But, before STAGE200 (Welcome to Installer).


REM vdelay 5000

verrlvl 0