@echo off

REM Reserved for custom error message displaying.

REM To automatically include this file on the installer, add FDTHANK.BAT to
REM the MKSETUP.LST installer setup file list.

REM If a language file FDTHANK.DEF exists, it will be automatically loaded
REM prior to running this file.

REM When an installation completes successfully, this file will be called
REM immediately before the script returns the user to the command prompt.

