@echo off

REM THEMENUL, Default Installer Theme.

REM Screen Foreground, Background and Fill Character
set _SFG=Gray
set _SBG=Blue
set _SFC=0xB0

REM Title Bar Foreground, Background and Highlight Colors
set _TFG=Black
set _TBG=Gray
set _THC=Red

REM Window Foreground, Background and Highlight Colors
set _FFG=Black
set _FHC=Red
set _FBG=Gray
set _FBS=single
set _FCS=0x1e

REM Choice Yes and No Colors
set _CYC=Green
set _CNC=Red

REM Control-C Foreground, Background and Highlight Colors
set _CFG=White
set _CHC=Yellow
set _CBG=Red
set _CBS=double
set _CCC=White
set _CAC=Yellow
set _CCS=0x1f

REM Pause Bar and Clock Colors
set _PBG=Blue
set _PBC=LightGreen
set _PCC=LightCyan

verrlvl 0
