@echo off

REM THEMEDEF, Default Installer Theme.

REM Screen Foreground, Background and Fill Character
set TSF=Gray
set TSB=Blue
set TSC=0xB0

REM Title Bar Foreground, Background and Highlight Colors
set TTF=Black
set TTB=Gray
set TTH=Red

REM Window Foreground, Background and Highlight Colors
set TFF=Black
set TFH=Red
set TFP=Blue
set TFB=Gray
set TFS=single shadow
set TFC=0x1e

REM Control-C Foreground, Background and Highlight Colors
set TCF=White
set TCH=Yellow
set TCB=Red
set TCS=double shadow
set TCC=0x1f

REM Pause Bar and Clock Colors
set TPB=Blue
set TPF=LightGreen
set TPH=LightCyan

verrlvl 0
