@echo off

REM THEMENUL, Default Installer Theme.

REM Screen Foreground, Background and Fill Character
set FDI_SFG=Gray
set FDI_SBG=Blue
set FDI_SFC=0xB0

REM Title Bar Foreground, Background and Highlight Colors
set FDI_TFG=Black
set FDI_TBG=Gray
set FDI_THC=Red

REM Window Foreground, Background and Highlight Colors
set FDI_FFG=Black
set FDI_FHC=Red
set FDI_FBG=Gray
set FDI_FBS=single
set FDI_FCS=0x1e

REM Choice Yes and No Colors
set FDI_CYC=Green
set FDI_CNC=Red

REM Control-C Foreground, Background and Highlight Colors
set FDI_CFG=White
set FDI_CHC=Yellow
set FDI_CBG=Red
set FDI_CBS=double
set FDI_CCC=White
set FDI_CAC=Yellow
set FDI_CCS=0x1f

REM Pause Bar and Clock Colors
set FDI_PBG=Blue
set FDI_PBC=LightGreen
set FDI_PCC=LightCyan
