@echo off

REM THEMEADV, Advanced Installer Theme.

REM Screen Foreground, Background and Fill Character
set FDI_SFG=Gray
set FDI_SBG=Red
set FDI_SFC=0xB0

REM Title Bar Foreground, Background and Highlight Colors
set FDI_TFG=White
set FDI_TBG=Red
set FDI_THC=Yellow

REM Window Foreground, Background and Highlight Colors
set FDI_FFG=White
set FDI_FHC=LightGreen
set FDI_FBG=Red
set FDI_FBS=double
set FDI_FCS=0x1e

REM Choice Yes and No Colors
set FDI_CYC=White
set FDI_CNC=Yellow

REM Control-C Foreground, Background and Highlight Colors
set FDI_CFG=White
set FDI_CHC=Yellow
set FDI_CBG=Red
set FDI_CBS=single
set FDI_CCC=White
set FDI_CAC=Yellow
set FDI_CCS=0x1f

REM Pause Bar and Clock Colors
set FDI_PBG=Red
set FDI_PBC=White
set FDI_PCC=Yellow
