@echo off

REM THEMEADV, Advanced Installer Theme.

REM Screen Foreground, Background and Fill Character
set _SFG=Gray
set _SBG=Red
set _SFC=0xB0

REM Title Bar Foreground, Background and Highlight Colors
set _TFG=White
set _TBG=Red
set _THC=Yellow

REM Window Foreground, Background and Highlight Colors
set _FFG=White
set _FHC=LightGreen
set _FBG=Red
set _FBS=double
set _FCS=0x1e

REM Choice Yes and No Colors
set _CYC=White
set _CNC=Yellow

REM Control-C Foreground, Background and Highlight Colors
set _CFG=White
set _CHC=Yellow
set _CBG=Red
set _CBS=single
set _CCC=White
set _CAC=Yellow
set _CCS=0x1f

REM Pause Bar and Clock Colors
set _PBG=Red
set _PBC=White
set _PCC=Yellow

verrlvl 0
